### ISSUE TITLE
Unexpected token ;

### ISSUE THREAD

**Issue by jpstotz** [node-projects/esprima-next#28]
Parsing https://cdnjs.cloudflare.com/ajax/libs/vue/3.1.3/vue.runtime.esm-browser.js ends up in the error 
`Error: Line 1169: Unexpected token ;`

Pseudo code:
```
let esprima = require('esprima-next');
esprima.parse(<file downloaded from https://cdnjs.cloudflare.com/ajax/libs/vue/3.1.3/vue.runtime.esm-browser.js>);
```

Relevant code section that causes the error:

```
class ComputedRefImpl {
    _setter;
    _value;
    _dirty = true;
    effect;
    __v_isRef = true;
    ["__v_isReadonly" /* IS_READONLY */]; // <-- line 1169
    constructor(getter, _setter, isReadonly) {
        ...
```

Used esprima-next version: 5.8.1

**Comment by jogibear9988** [comment]
sorry, didn't see this. I look into it

**Comment by jpstotz** [comment]
Thanks for fixing :)

**Comment by jogibear9988** [comment]
I did't know that this was possible in ES classes 😊
