### ISSUE TITLE
assignment of class declaration fails on super keyword

### ISSUE THREAD

**Issue by EricJergensen** [node-projects/esprima-next#29]
### Steps to reproduce

```js
esprima.parse('e = class D extends Date { constructor() { super() } }')
```

### Expected output

This parses without the super(). It also parses without the assignment.

In the case of assignment with super(), the resulting ClassExpression that is the .right of the ExpressionStatement should have a constructor with a CallExpression type: 'Super'

### Actual output

throws: 'super' keyword unexpected here

**Comment by pYr0x** [comment]
running into the same issue.
did a previous version not have this error?
