### ISSUE TITLE
Spread fails

### ISSUE THREAD

**Issue by orlandoaleman** [node-projects/esprima-next#30]
I want to get the rest of the arguments, like _.omit() of lodash does. But I can't get them

Example:

```
function (args = {}) {
  let { callbackOK, callbackERROR, ...argsWS } = args;
  ..
}
```

**Comment by jogibear9988** [comment]
Dont know what you mean...

If I parse this code:

     function a(args = {}) {
        let { callbackOK, callbackERROR, ...argsWS } = args;

    }

it works for me. (function needs a name or it's invalid javascript)

see
<img width="985" alt="Bildschirmfoto 2022-06-04 um 07 49 34" src="https://user-images.githubusercontent.com/364896/171986479-25c4d271-947b-4724-a673-a24b7d01a952.png">
:
