### ISSUE TITLE
Include fixes from mostafa-hisham/esprima

### ISSUE THREAD

**Issue by mrienstra** [node-projects/esprima-next#36]
I ran across:
https://github.com/mostafa-hisham/esprima/tree/develop

Via:
https://github.com/jquery/esprima/network

À la #24, #35, #32 & #6, thought you might want to check to see if any of their changes are useful and unique.

_(you've probably already seen it, just opening this in case, as I don't see a prior mention of it)_

**Comment by jogibear9988** [comment]
The only thing I see they added ist this class: custom-tokenizer.ts 
but I don't know what it's for
https://github.com/jquery/esprima/compare/main...mostafa-hisham:esprima:develop?expand=1&w=1#diff-9a793982fb1de88697c1b95b5133faac27fa9ab7721d4b827fd613435f879632
